// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmY-dKTEYRo7LaGQY247IRx4ioRsLQym0',
    appId: '1:636016915209:web:e2b500dbb7afab4318d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    authDomain: 'judica-cc7c2.firebaseapp.com',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vx2vUEMXciCEq9bgMKj_H42Jzz8TH1w',
    appId: '1:636016915209:android:b2f3a98c2c7e346f18d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVP9lh04NrEp7-YLEX3Nhm5dsriHFVKQ',
    appId: '1:636016915209:ios:ef9a00857354675218d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
    androidClientId: '636016915209-7artoro9nhuvjc0s9rb9eomfsh114quu.apps.googleusercontent.com',
    iosClientId: '636016915209-ls73sda5r15jc334s4e9mamjt66h8bbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.judica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVP9lh04NrEp7-YLEX3Nhm5dsriHFVKQ',
    appId: '1:636016915209:ios:ef9a00857354675218d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
    androidClientId: '636016915209-7artoro9nhuvjc0s9rb9eomfsh114quu.apps.googleusercontent.com',
    iosClientId: '636016915209-ls73sda5r15jc334s4e9mamjt66h8bbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.judica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmY-dKTEYRo7LaGQY247IRx4ioRsLQym0',
    appId: '1:636016915209:web:96f9183b97c7a5d618d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    authDomain: 'judica-cc7c2.firebaseapp.com',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );
}
